### ISSUE TITLE
The animated text on the pilots roster sometimes "bleeds" into the right adjacent column

### ISSUE THREAD

**Issue by OmnesPotens** [Kuenaimaku/lancer-briefings#13]
#### Summary
Currenlty it is possible for the `pilotCode` `vuewriter` element to bleed/overflow into the column to the right of it. It should be constrained so that it cannot overflow like this. I have opened an issue for this on the `vuewriter` repo, more context [here](https://github.com/quelchx/vue-writer/issues/10).

![image](https://user-images.githubusercontent.com/21691862/191048480-8ee2710b-9545-42f9-9f6d-8d7febaadb33.png)

#### Potential Solutions
- [ ] Break the `pilotCode` string into pieces and pass it in as an actual array, this should force each passed in string to only be written after the previous one has been removed. (This probably isn't a complete solution and the animated effect wouldn't look as great)
- [ ] Wait for the above linked issue/feature request to be completed and update to the new version
- [ ] Replace `vuewriter` with a different library that can handle this element and the animation (with custom styling)
  Potential replacements:
    - [typeit](https://github.com/alexmacarthur/typeit) Used by the compcon app
    - [vue-typer](https://github.com/cngu/vue-typer) Not an option until [Vue3 support](https://github.com/cngu/vue-typer/issues/46) is implemented, which may never happen since it seems the project has not been updated since 2017

**Comment by Kuenaimaku** [comment]
I think going with the typeit implementation would probably be for the best, and I can look into it this weekend, unless you have the capacity to work on it earlier.

**Comment by OmnesPotens** [comment]
> I think going with the typeit implementation would probably be for the best, and I can look into it this weekend, unless you have the capacity to work on it earlier.

I likely won't get a chance this week unfortunately
